# Generated by Django 5.0.3 on 2024-03-27 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ModelName', models.CharField(blank=True, max_length=100, null=True)),
                ('Brand', models.CharField(blank=True, max_length=100, null=True)),
                ('Transmission', models.CharField(blank=True, max_length=100, null=True)),
                ('Discription', models.CharField(blank=True, max_length=100, null=True)),
                ('Fuel', models.CharField(blank=True, max_length=100, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('PriceD', models.IntegerField(blank=True, null=True)),
                ('Mileage', models.IntegerField(blank=True, null=True)),
                ('Seats', models.IntegerField(blank=True, null=True)),
                ('Luggage', models.IntegerField(blank=True, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='Car_Image')),
            ],
        ),
    ]
