# Generated by Django 5.0.3 on 2024-04-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackApp', '0004_blogdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardb',
            name='PriceDD',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
