# Generated by Django 5.0.3 on 2024-04-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackdb',
            old_name='Message',
            new_name='Review',
        ),
        migrations.RemoveField(
            model_name='feedbackdb',
            name='Subject',
        ),
        migrations.AddField(
            model_name='feedbackdb',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='Feedback_Image'),
        ),
    ]
