# Generated by Django 5.0.3 on 2024-04-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontApp', '0003_rename_feedbackdb_reviewdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewdb',
            name='Review',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
