# Generated by Django 5.0.3 on 2024-04-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontApp', '0004_alter_reviewdb_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.CharField(blank=True, max_length=100, null=True)),
                ('Number', models.IntegerField(blank=True, null=True)),
                ('PickUpL', models.CharField(blank=True, max_length=200, null=True)),
                ('DropOffL', models.CharField(blank=True, max_length=200, null=True)),
                ('PickUp', models.DateField()),
                ('DropOff', models.DateField()),
                ('PickUpT', models.DateTimeField()),
            ],
        ),
    ]
