# Generated by Django 5.0.3 on 2024-04-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontApp', '0005_bookdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdb',
            name='DropOffL',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookdb',
            name='PickUpT',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
