# Generated by Django 5.0.3 on 2024-04-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontApp', '0006_alter_bookdb_dropoffl_alter_bookdb_pickupt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdb',
            name='DropOff',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookdb',
            name='PickUp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
