# Generated by Django 5.0.3 on 2024-04-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontApp', '0007_alter_bookdb_dropoff_alter_bookdb_pickup'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverJobDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.CharField(blank=True, max_length=100, null=True)),
                ('Number', models.IntegerField(blank=True, null=True)),
                ('Experience', models.CharField(blank=True, max_length=200, null=True)),
                ('Resume', models.FileField(upload_to='Resume_Driver')),
            ],
        ),
    ]
