# Generated by Django 5.0.3 on 2024-04-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontApp', '0008_driverjobdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverjobdb',
            name='Car',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
